### ISSUE TITLE
CORS Error

### ISSUE THREAD

**Issue by pritipsingh** [apify/apify-client-js#427]
Hey y'all I am trying to integrate langchain using apify-client & constantly getting CORS error. I am copying the exact code given in the example [here](https://js.langchain.com/docs/modules/data_connection/document_loaders/integrations/web_loaders/apify_dataset)

<img width="816" alt="Screenshot 2023-10-03 at 4 07 36 AM" src="https://github.com/apify/apify-client-js/assets/85965351/a4e0e758-f9db-4bf2-8ed4-4e4089927aae">

**Comment by mtrunkat** [comment]
@drobnikj, @jirimoravcik - could you take a look?

**Comment by jirimoravcik** [comment]
Hello @pritipsingh,
could you provide more details on the app you're running at `http://localhost:3001`? If it's a frontend application, then you may need to adjust its CORS policy headers for your code to work correctly. But right now I can't help you more since I'm lacking the necessary context.

Thanks
